export type Category = "entrées" | "plats" | "desserts" | "accompagnements";

export type IngredientKind = "continuous" | "whole" | "fractional" | "fixed";

export type Ingredient = {
  label: string;
  amount?: number;
  unit?: string;
  kind?: IngredientKind;
  optional?: boolean;
};

export type Recipe = {
  slug: string;
  title: string;
  category: Category;
  portions: number;
  prep: string;
  cook?: string;
  rest?: string;
  total?: string;
  illustration: string;
  ingredients: Ingredient[];
  steps: string[];
  note?: string;
};

export const categoryMeta: Record<Category, { label: string; color: string; icon: string }> = {
  entrées: { label: "Entrées", color: "#AAB494", icon: "✦" },
  plats: { label: "Plats", color: "#EEC3A0", icon: "✦" },
  desserts: { label: "Desserts", color: "#E7D17C", icon: "✦" },
  accompagnements: { label: "Accompagnements", color: "#D99B7B", icon: "✦" },
};

export const recipes: Recipe[] = [
  {
    slug: "banana-bread-healthy",
    title: "Banana bread healthy",
    category: "desserts",
    portions: 6,
    prep: "15 min",
    cook: "45 min à 180 °C",
    illustration: "/illustrations/banana-bread.png",
    ingredients: [
      { amount: 3, label: "bananes", kind: "whole" },
      { amount: 2, label: "œufs", kind: "whole" },
      { amount: 100, unit: "g", label: "yaourt grec" },
      { amount: 200, unit: "g", label: "farine" },
      { amount: 0.5, unit: "sachet", label: "levure chimique", kind: "fractional" },
      { amount: 100, unit: "g", label: "chocolat noir en morceaux" },
      { amount: 10, label: "cerneaux de noix", kind: "whole", optional: true },
      { amount: 0.25, unit: "c. à café", label: "cannelle", kind: "fractional", optional: true },
    ],
    steps: [
      "Préchauffez le four à 180 °C.",
      "Écrasez 2 bananes dans un saladier, puis mélangez-les avec le yaourt grec et les œufs.",
      "Ajoutez la farine en plusieurs fois et mélangez jusqu’à obtenir une pâte lisse.",
      "Ajoutez la levure chimique, puis la cannelle si vous en utilisez.",
      "Incorporez le chocolat en morceaux et 6 cerneaux de noix concassés.",
      "Versez la pâte dans un moule à cake chemisé de papier cuisson.",
      "Coupez la banane restante en deux dans la longueur et déposez-la sur le dessus. Ajoutez le reste des noix et quelques morceaux de chocolat si vous le souhaitez.",
      "Enfournez 45 minutes. Vérifiez la cuisson avec la lame d’un couteau, puis laissez refroidir avant de démouler.",
    ],
    note: "Vous pouvez remplacer le chocolat par 3 c. à soupe de beurre de cacahuète.",
  },
  {
    slug: "carpaccio-saumon-fume",
    title: "Carpaccio de saumon fumé",
    category: "entrées",
    portions: 2,
    prep: "15 min",
    illustration: "/illustrations/carpaccio-saumon.png",
    ingredients: [
      { amount: 4, label: "tranches de saumon fumé", kind: "whole" },
      { amount: 3, unit: "c. à soupe", label: "huile d’olive" },
      { amount: 0.5, label: "citron jaune (jus et zeste)", kind: "fractional" },
      { amount: 1, unit: "c. à soupe", label: "câpres" },
      { amount: 1, unit: "c. à café", label: "aneth séché" },
      { amount: 0.25, unit: "c. à café", label: "échalote séchée", kind: "fractional" },
      { amount: 0.125, unit: "c. à café", label: "ail en poudre", kind: "fractional" },
      { label: "poivre", kind: "fixed" },
      { amount: 2, unit: "pincées", label: "piment d’Espelette", kind: "fixed" },
    ],
    steps: [
      "Répartissez le saumon fumé en tranches fines sur deux assiettes plates et froides, en les faisant légèrement se chevaucher.",
      "Mélangez l’huile d’olive, le jus de citron, l’échalote séchée, l’ail en poudre et le poivre.",
      "Nappez le saumon de vinaigrette.",
      "Parsemez de câpres, d’aneth, de piment d’Espelette et de zeste de citron. Servez bien frais.",
    ],
    note: "Ne salez pas la vinaigrette : le saumon fumé et les câpres apportent déjà assez de sel. Servez dans les 10 minutes après avoir ajouté le citron.",
  },
  {
    slug: "courgettes-marinees-citron-thym",
    title: "Courgettes marinées citron thym",
    category: "entrées",
    portions: 2,
    prep: "15 min",
    rest: "Marinade : 2 h",
    illustration: "/illustrations/courgettes-marinees.png",
    ingredients: [
      { amount: 2, label: "courgettes", kind: "whole" },
      { amount: 6, unit: "c. à soupe", label: "huile d’olive" },
      { amount: 1, label: "citron vert (jus et zeste)", kind: "fractional" },
      { amount: 2, unit: "c. à soupe", label: "melfort" },
      { amount: 1, unit: "c. à soupe", label: "thym séché" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
      { amount: 0.5, unit: "c. à café", label: "échalote séchée", kind: "fractional" },
      { amount: 0.25, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { label: "sel et poivre", kind: "fixed" },
      { amount: 10, label: "noisettes", kind: "whole" },
    ],
    steps: [
      "Mélangez l’huile d’olive, le jus de citron vert, l’ail et l’échalote séchés, les herbes de Provence, le thym, le melfort, le sel et le poivre.",
      "Coupez les courgettes en fines lanières dans la longueur. Faites-les griller à feu vif 2 à 3 minutes de chaque côté, sans trop les ramollir.",
      "Versez la marinade sur les courgettes encore chaudes et laissez mariner 2 heures au frais.",
      "Au moment de servir, ajoutez les noisettes concassées et torréfiées, ainsi que le zeste de citron vert.",
    ],
    note: "Vous pouvez ajouter des copeaux de parmesan au moment du dressage.",
  },
  {
    slug: "crispy-rice-salade",
    title: "Crispy rice salade",
    category: "plats",
    portions: 2,
    prep: "20 min",
    cook: "35 min",
    illustration: "/illustrations/crispy-rice.png",
    ingredients: [
      { amount: 2, unit: "verres", label: "riz basmati" },
      { amount: 1, unit: "c. à soupe", label: "sauce sriracha" },
      { amount: 2, unit: "c. à soupe", label: "huile de sésame" },
      { amount: 2, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 1, label: "avocat", kind: "whole" },
      { amount: 0.5, label: "concombre", kind: "fractional" },
      { amount: 10, label: "cacahuètes", kind: "whole" },
      { amount: 1, label: "boîte de thon", kind: "whole" },
      { label: "piment d’Espelette", kind: "fixed" },
      { amount: 1, unit: "c. à café", label: "menthe séchée", optional: true },
      { amount: 2, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 3, unit: "c. à soupe", label: "vinaigre de riz ou assaisonnement sushi" },
      { amount: 4, unit: "c. à soupe", label: "sauce soja" },
      { amount: 2, unit: "c. à soupe", label: "jus de citron" },
      { label: "ail séché, oignon séché, poivre et gingembre séché", kind: "fixed" },
    ],
    steps: [
      "Préchauffez le four à 220 °C.",
      "Faites cuire le riz selon les indications du paquet. Étalez-le sur une plaque recouverte de papier cuisson, puis mélangez avec la sriracha, la sauce soja et l’huile de sésame.",
      "Enfournez 35 minutes ou davantage selon le croustillant souhaité, en remuant toutes les 10 minutes.",
      "Laissez refroidir le riz. Coupez l’avocat et le concombre en cubes.",
      "Mélangez les ingrédients de la sauce et ajustez l’assaisonnement.",
      "Concassez les cacahuètes.",
      "Assemblez les légumes, le riz, le thon et la sauce. Parsemez de cacahuètes, de menthe et de piment d’Espelette.",
    ],
    note: "Le thon peut être remplacé par des œufs. Vous pouvez aussi ajouter ou remplacer le concombre par du chou, des champignons ou des edamames.",
  },
  {
    slug: "effiloche-de-poulet",
    title: "Effiloché de poulet",
    category: "plats",
    portions: 1,
    prep: "10 min",
    cook: "45 min",
    illustration: "/illustrations/effiloche-poulet.png",
    ingredients: [
      { amount: 1, label: "blanc de poulet", kind: "whole" },
      { amount: 2, unit: "c. à soupe", label: "concentré de tomates" },
      { amount: 2, unit: "c. à soupe", label: "sauce tomate" },
      { amount: 1, label: "cube de bouillon", kind: "whole" },
      { amount: 0.5, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "oignon séché" },
      { amount: 1, unit: "c. à café", label: "paprika" },
      { amount: 0.25, unit: "c. à café", label: "cumin", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
      { label: "piment d’Espelette ou 1 c. à soupe de sauce sriracha", kind: "fixed" },
      { label: "sel, poivre et huile d’olive", kind: "fixed" },
    ],
    steps: [
      "Dans une casserole, faites revenir les épices dans un filet d’huile d’olive pendant 30 secondes.",
      "Ajoutez la sauce tomate, le concentré de tomates, un peu d’eau, le cube de bouillon et le blanc de poulet.",
      "Faites cuire à feu très doux 30 à 45 minutes en ajoutant de l’eau si nécessaire.",
      "Effilochez le poulet à l’aide de deux fourchettes, mélangez-le à la sauce et poursuivez la cuisson 5 minutes à feu très doux.",
    ],
  },
  {
    slug: "korean-sticky-beef",
    title: "Korean sticky beef",
    category: "plats",
    portions: 2,
    prep: "20 min",
    cook: "20 min",
    illustration: "/illustrations/korean-sticky-beef.png",
    ingredients: [
      { amount: 250, unit: "g", label: "bœuf haché" },
      { amount: 1, label: "oignon", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "ail séché" },
      { amount: 3, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 1, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 1, unit: "c. à café", label: "huile de sésame" },
      { amount: 1, unit: "c. à soupe", label: "sauce sriracha" },
      { amount: 1, unit: "c. à café", label: "sauce huître", optional: true },
      { label: "piment d’Espelette, sésame, ciboulette, jus de citron et poivre", kind: "fixed" },
    ],
    steps: [
      "Émincez l’oignon, faites-le cuire jusqu’à ce qu’il soit tendre, puis réservez-le.",
      "Faites cuire le bœuf haché en l’émiettant. Ajoutez l’ail, 1 c. à soupe de sauce soja, l’huile de sésame, le poivre et le piment d’Espelette. Faites dorer à feu vif.",
      "Ajoutez la sriracha, le reste de sauce soja, le sirop d’agave et, si vous en utilisez, la sauce huître. Remettez l’oignon et laissez mijoter 2 minutes en remuant.",
      "Servez avec la ciboulette, le sésame, un peu de piment et éventuellement un filet de citron.",
    ],
    note: "Très bon avec du riz thaï assaisonné d’assaisonnement sushi.",
  },
  {
    slug: "pates-chorizo-ricotta",
    title: "Pâtes chorizo ricotta",
    category: "plats",
    portions: 2,
    prep: "15 min",
    cook: "15 min",
    illustration: "/illustrations/pates-chorizo-ricotta.png",
    ingredients: [
      { label: "fusilli pour 2 personnes", kind: "fixed" },
      { amount: 0.5, label: "chorizo", kind: "fractional" },
      { amount: 2, unit: "c. à soupe", label: "ricotta" },
      { amount: 4, unit: "c. à soupe", label: "sauce tomate" },
      { label: "piment d’Espelette, sel et poivre", kind: "fixed" },
      { label: "parmesan râpé", kind: "fixed" },
    ],
    steps: [
      "Faites cuire les pâtes dans une grande casserole d’eau bouillante salée, en les sortant 1 minute avant la fin du temps indiqué. Réservez deux petites louches d’eau de cuisson.",
      "Retirez la peau du chorizo, coupez-le en petits morceaux et faites-le revenir 3 minutes à feu moyen.",
      "Ajoutez la sauce tomate et le piment d’Espelette, puis laissez cuire 2 minutes.",
      "Ajoutez l’eau de cuisson et les pâtes. Mélangez pour les enrober de sauce.",
      "Étalez la ricotta dans le fond des assiettes, salez et poivrez. Ajoutez les pâtes, parsemez de parmesan et ajustez l’assaisonnement.",
    ],
    note: "Cette recette se réchauffe mal à cause de la ricotta. Vous pouvez ajouter du zeste de citron au dressage.",
  },
  {
    slug: "pates-burrata-pistaches",
    title: "Pâtes burrata pistaches",
    category: "plats",
    portions: 1,
    prep: "10 min",
    cook: "12 min",
    total: "22 min",
    illustration: "/illustrations/pates-burrata-pistaches.png",
    ingredients: [
      { label: "rigatoni pour 1 personne", kind: "fixed" },
      { amount: 2, unit: "poignées", label: "pistaches" },
      { amount: 1, label: "burrata", kind: "whole" },
      { label: "sel, poivre et huile d’olive", kind: "fixed" },
      { label: "zeste de citron et basilic frais", kind: "fixed", optional: true },
    ],
    steps: [
      "Faites cuire les rigatoni dans une casserole d’eau salée, selon le temps indiqué sur le paquet.",
      "Concassez les pistaches et torréfiez-les à sec dans une poêle chaude 1 à 2 minutes.",
      "Sortez la burrata du réfrigérateur une dizaine de minutes avant de servir.",
      "Dressez les pâtes, ajoutez la burrata entière ou déchirée, puis parsemez de pistaches. Terminez avec un filet d’huile d’olive, du sel, du poivre et du zeste de citron si vous en utilisez.",
    ],
    note: "Servez immédiatement, en laissant chacun ouvrir la burrata dans son assiette.",
  },
  {
    slug: "pates-thon-citron-ricotta",
    title: "Pâtes thon, citron, ricotta",
    category: "plats",
    portions: 2,
    prep: "10 min",
    cook: "10 à 12 min",
    illustration: "/illustrations/pates-thon-citron-ricotta.png",
    ingredients: [
      { label: "fusilli pour 2 personnes", kind: "fixed" },
      { amount: 3, unit: "c. à soupe", label: "ricotta" },
      { amount: 1, label: "boîte de thon", kind: "whole" },
      { amount: 1, unit: "c. à soupe", label: "jus de citron" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
      { label: "sel, poivre et huile d’olive", kind: "fixed" },
    ],
    steps: [
      "Faites cuire les pâtes selon les indications du paquet.",
      "Hors du feu, ajoutez le thon, le jus de citron, un filet d’huile d’olive, le sel, le poivre, les herbes de Provence et la ricotta.",
      "Mélangez jusqu’à obtenir une préparation homogène et servez chaud.",
    ],
    note: "Cette recette se réchauffe mal à cause de la ricotta. Vous pouvez ajouter du zeste de citron au dressage.",
  },
  {
    slug: "poke-bowl",
    title: "Poke bowl",
    category: "plats",
    portions: 1,
    prep: "20 min",
    cook: "15 min",
    rest: "Marinade : 30 min minimum",
    illustration: "/illustrations/poke-bowl.png",
    ingredients: [
      { amount: 1, label: "pavé de saumon", kind: "whole" },
      { amount: 0.5, unit: "verre", label: "riz à sushi" },
      { amount: 2, unit: "c. à soupe", label: "assaisonnement sushi" },
      { amount: 0.5, label: "avocat", kind: "fractional" },
      { amount: 0.25, label: "mangue", kind: "fractional", optional: true },
      { amount: 0.5, unit: "c. à café", label: "graines de sésame", kind: "fractional" },
      { amount: 4, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 1, unit: "c. à café", label: "sirop d’agave" },
      { amount: 0.25, unit: "c. à café", label: "huile de sésame", kind: "fractional" },
      { label: "ail séché et gingembre en poudre", kind: "fixed" },
    ],
    steps: [
      "Coupez le saumon en cubes.",
      "Mélangez les ingrédients de la marinade, versez-la sur le saumon et réservez au frais au moins 30 minutes. Deux heures sont idéales.",
      "Faites cuire le riz selon les indications du paquet.",
      "Assaisonnez le riz avec l’assaisonnement sushi, goûtez et laissez refroidir.",
      "Coupez l’avocat et, si vous en utilisez, la mangue en cubes.",
      "Disposez le riz, le saumon, l’avocat et la mangue dans l’assiette. Versez le reste de marinade sur le riz et parsemez de sésame.",
    ],
    note: "Vous pouvez ajouter des algues nori, des oignons frits ou des edamames.",
  },
  {
    slug: "poulet-abricots-secs",
    title: "Poulet abricots secs",
    category: "plats",
    portions: 1,
    prep: "15 min",
    cook: "20 min",
    total: "35 min",
    illustration: "/illustrations/poulet-abricots-secs.png",
    ingredients: [
      { amount: 1, label: "blanc de poulet", kind: "whole" },
      { amount: 6, label: "abricots secs", kind: "whole" },
      { amount: 0.25, label: "oignon", kind: "fractional" },
      { amount: 10, label: "noix de cajou ou amandes effilées", kind: "whole" },
      { amount: 0.5, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { label: "cumin, 4 épices et curcuma", kind: "fixed" },
      { amount: 1, unit: "c. à café", label: "sirop d’agave" },
      { label: "jus de citron", kind: "fixed", optional: true },
      { label: "huile d’olive, sel, poivre, eau et 1/2 cube de bouillon", kind: "fixed" },
      { label: "semoule en quantité individuelle", kind: "fixed" },
    ],
    steps: [
      "Émincez l’oignon et faites-le revenir 5 minutes dans une poêle avec un filet d’huile d’olive, en ajoutant un peu d’eau si besoin.",
      "Coupez le poulet en cubes. Ajoutez les épices et le poulet, puis faites revenir 3 minutes à feu moyen.",
      "Coupez les abricots secs en lamelles. Ajoutez-les avec un verre d’eau, le cube de bouillon et le sirop d’agave. Laissez mijoter 10 à 20 minutes en ajoutant de l’eau au besoin.",
      "Préparez la semoule avec de l’eau bouillante et laissez reposer 5 minutes.",
      "Torréfiez les noix de cajou ou les amandes effilées une minute à la poêle.",
      "Ajoutez la semoule au poulet, remuez 1 à 2 minutes, puis ajoutez un filet de jus de citron hors du feu. Parsemez de fruits secs et servez.",
    ],
    note: "Vous pouvez faire cette recette avec des pruneaux ou des raisins secs. Dans ce cas, privilégiez les amandes effilées.",
  },
  {
    slug: "poulet-imperial",
    title: "Poulet impérial",
    category: "plats",
    portions: 1,
    prep: "20 min",
    cook: "20 min",
    rest: "Marinade : 30 min minimum",
    illustration: "/illustrations/poulet-imperial.png",
    ingredients: [
      { amount: 1, label: "blanc de poulet", kind: "whole" },
      { amount: 10, label: "noix de cajou", kind: "whole" },
      { amount: 0.5, label: "poivron", kind: "fractional" },
      { amount: 0.25, label: "oignon", kind: "fractional" },
      { amount: 0.5, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { amount: 2, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 1, unit: "c. à soupe", label: "sirop d’agave" },
      { label: "piment d’Espelette", kind: "fixed", optional: true },
      { amount: 0.5, unit: "verre", label: "riz thaï" },
      { label: "ciboulette séchée", kind: "fixed", optional: true },
      { label: "huile d’olive", kind: "fixed" },
    ],
    steps: [
      "Mélangez la sauce soja, le sirop d’agave et l’ail. Coupez le poulet en cubes, ajoutez-le à la marinade et laissez reposer au moins 30 minutes.",
      "Émincez l’oignon et faites-le cuire dans une poêle avec un filet d’huile d’olive.",
      "Ajoutez le poivron en cubes et faites revenir 10 minutes, avec un peu d’eau si nécessaire.",
      "Faites cuire le riz selon les indications du paquet.",
      "Ajoutez le poulet, la marinade et le piment d’Espelette à la poêle. Faites cuire 5 minutes.",
      "Ajoutez les noix de cajou et poursuivez 3 minutes. Servez avec le riz et la ciboulette.",
    ],
  },
  {
    slug: "poulet-iranien-fesenjan-simplifie",
    title: "Poulet iranien (Fesenjan simplifié)",
    category: "plats",
    portions: 1,
    prep: "20 min",
    cook: "50 min",
    total: "70 min",
    illustration: "/illustrations/poulet-iranien.png",
    ingredients: [
      { amount: 1, label: "oignon", kind: "fractional" },
      { amount: 1, label: "blanc de poulet", kind: "whole" },
      { amount: 4, unit: "poignées", label: "graines de grenade" },
      { amount: 1, unit: "c. à soupe", label: "cannelle" },
      { amount: 0.5, unit: "c. à café", label: "muscade", kind: "fractional" },
      { amount: 1.5, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 2, unit: "c. à soupe", label: "jus de citron" },
      { amount: 12, label: "cerneaux de noix", kind: "whole" },
      { amount: 1, unit: "c. à café", label: "4 épices", optional: true },
      { label: "sel et poivre", kind: "fixed" },
    ],
    steps: [
      "Torréfiez les cerneaux de noix à sec 1 à 2 minutes. Réservez-en quelques-uns et concassez le reste.",
      "Réservez quelques grains de grenade pour le dressage et pressez le reste pour en extraire le jus.",
      "Faites dorer le poulet avec un filet d’huile 4 à 5 minutes sur toutes les faces, puis réservez.",
      "Faites revenir l’oignon émincé 3 à 4 minutes dans la même poêle.",
      "Ajoutez les noix, la cannelle, les 4 épices et la muscade. Faites revenir une minute.",
      "Versez le jus de grenade, le sirop d’agave et 2 verres d’eau. Couvrez et laissez mijoter 20 minutes en remuant régulièrement.",
      "Remettez le poulet et le jus de citron dans la sauce. Laissez mijoter 20 à 25 minutes à feu doux, en ajoutant un peu d’eau si besoin.",
      "Rectifiez l’assaisonnement et servez avec les grains de grenade et les noix réservées.",
    ],
    note: "À servir avec du riz thaï ou basmati.",
  },
  {
    slug: "poulet-piccata",
    title: "Poulet piccata",
    category: "plats",
    portions: 2,
    prep: "20 min",
    cook: "15 min",
    illustration: "/illustrations/poulet-piccata.png",
    ingredients: [
      { amount: 2, label: "blancs de poulet", kind: "whole" },
      { amount: 3, unit: "c. à soupe", label: "farine" },
      { amount: 2, unit: "c. à soupe", label: "jus de citron" },
      { amount: 2, unit: "c. à soupe", label: "vin blanc" },
      { amount: 3, unit: "c. à soupe", label: "bouillon de volaille en poudre" },
      { amount: 1, label: "oignon", kind: "fractional" },
      { amount: 0.25, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "thym séché", optional: true },
      { amount: 1, unit: "c. à soupe", label: "herbes de Provence" },
      { amount: 2, unit: "c. à soupe", label: "câpres" },
      { amount: 1, unit: "c. à soupe", label: "miso" },
      { amount: 1, unit: "c. à soupe", label: "huile d’olive" },
      { amount: 3, unit: "c. à soupe", label: "eau" },
      { label: "sel et poivre", kind: "fixed" },
    ],
    steps: [
      "Émincez l’oignon et faites-le revenir dans une poêle avec un filet d’huile jusqu’à ce qu’il soit tendre. Réservez.",
      "Coupez chaque blanc de poulet en deux dans l’épaisseur pour obtenir 4 escalopes fines, puis aplatissez-les légèrement.",
      "Farinez les escalopes. Faites chauffer l’huile d’olive et cuisez le poulet 4 minutes par face à feu moyen. Salez, poivrez, ajoutez l’ail et réservez.",
      "Déglacez avec le vin blanc. Ajoutez le bouillon, l’eau, le jus de citron, le miso, le thym et les herbes de Provence.",
      "Ajoutez les câpres et l’oignon, puis laissez réduire. Épaississez avec une pincée de farine si besoin.",
      "Remettez le poulet dans la sauce et laissez mijoter 5 minutes. Goûtez, rectifiez et servez.",
    ],
  },
  {
    slug: "quiche-lorraine-epaisse",
    title: "Quiche lorraine épaisse",
    category: "plats",
    portions: 8,
    prep: "40 min",
    cook: "50 min à 180 °C",
    rest: "Repos : 30 min",
    illustration: "/illustrations/quiche-lorraine.png",
    ingredients: [
      { amount: 250, unit: "g", label: "farine type 55" },
      { amount: 125, unit: "g", label: "beurre froid" },
      { amount: 63, unit: "g", label: "eau froide" },
      { amount: 1, label: "œuf + 1 jaune", kind: "whole" },
      { label: "sel fin", kind: "fixed" },
      { amount: 400, unit: "g", label: "lard fumé" },
      { amount: 5, label: "œufs", kind: "whole" },
      { amount: 40, unit: "cl", label: "crème fraîche" },
      { amount: 20, unit: "cl", label: "lait" },
      { amount: 1, unit: "c. à café", label: "muscade" },
      { label: "sel et poivre", kind: "fixed" },
      { amount: 150, unit: "g", label: "emmental ou comté râpé" },
    ],
    steps: [
      "Mélangez la farine et le sel. Ajoutez le beurre froid coupé en morceaux et sablez la pâte du bout des doigts.",
      "Ajoutez l’œuf, le jaune et l’eau froide. Mélangez jusqu’à obtenir une pâte ferme, souple et à peine collante.",
      "Formez une boule, filmez-la et laissez reposer 30 minutes au frais.",
      "Préchauffez le four à 180 °C. Beurrez un moule à bords hauts, étalez la pâte, foncez le moule et piquez le fond.",
      "Découpez le lard fumé et faites-le revenir à la poêle 5 à 6 minutes, sans matière grasse. Égouttez-le.",
      "Battez les œufs, ajoutez la crème et le lait, puis le lard. Salez, poivrez, ajoutez la muscade et versez sur la pâte. Parsemez de fromage.",
      "Enfournez 50 minutes à 180 °C. Laissez reposer 10 minutes avant de servir.",
    ],
  },
  {
    slug: "riz-au-lait-de-coco",
    title: "Riz au lait de coco",
    category: "accompagnements",
    portions: 2,
    prep: "5 min",
    cook: "25 à 30 min",
    illustration: "/illustrations/riz-lait-coco.png",
    ingredients: [
      { amount: 1, unit: "verre", label: "riz thaï" },
      { amount: 0.5, label: "briquette de lait de coco", kind: "fractional" },
      { amount: 0.5, unit: "c. à café", label: "paprika fumé", kind: "fractional" },
      { label: "sel et poivre", kind: "fixed" },
    ],
    steps: [
      "Mettez le riz, 2 verres d’eau, le lait de coco, le sel et le poivre dans une casserole.",
      "Faites cuire à feu doux jusqu’à obtenir une texture crémeuse, en remuant souvent pour que le riz n’accroche pas.",
      "Disposez le riz dans les assiettes et saupoudrez de paprika fumé.",
    ],
    note: "Vous pouvez cuire le riz au cuiseur, puis le réchauffer à la poêle avec le lait de coco. Il accompagne très bien du poulet mariné au paprika fumé.",
  },
  {
    slug: "riz-saute-a-la-tomate",
    title: "Riz sauté à la tomate",
    category: "accompagnements",
    portions: 2,
    prep: "15 min",
    cook: "15 min",
    illustration: "/illustrations/riz-saute-tomate.png",
    ingredients: [
      { amount: 1, unit: "verre", label: "riz basmati" },
      { amount: 2, unit: "c. à soupe", label: "concentré de tomate" },
      { amount: 4, unit: "c. à soupe", label: "sauce tomate", optional: true },
      { amount: 1, label: "oignon", kind: "fractional" },
      { amount: 0.5, unit: "c. à soupe", label: "curcuma", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
      { label: "sel, poivre et huile d’olive", kind: "fixed" },
      { amount: 1, unit: "c. à soupe", label: "yaourt nature", optional: true },
    ],
    steps: [
      "Faites cuire le riz selon les indications du paquet, égouttez-le et réservez.",
      "Émincez l’oignon et faites-le cuire 10 minutes dans une poêle avec un filet d’huile d’olive. Ajoutez le curcuma, les herbes de Provence et le concentré de tomate, puis laissez cuire 1 minute.",
      "Ajoutez le riz, salez, poivrez et pressez-le avec une spatule pour qu’il soit en contact avec le fond de la poêle.",
      "Faites dorer 2 minutes à feu moyen. Remuez, pressez à nouveau et cuisez encore 3 minutes, jusqu’à ce qu’il soit légèrement doré et croustillant.",
    ],
    note: "Servez avec une cuillerée de yaourt nature. La menthe peut remplacer les herbes de Provence.",
  },
  {
    slug: "salade-de-concombre-a-l-asiatique",
    title: "Salade de concombre à l’asiatique",
    category: "accompagnements",
    portions: 2,
    prep: "10 min",
    rest: "Marinade : 30 min",
    illustration: "/illustrations/salade-concombre-asiatique.png",
    ingredients: [
      { amount: 1, label: "concombre", kind: "fractional" },
      { amount: 1, label: "oignon rouge", kind: "fractional" },
      { amount: 1, unit: "c. à soupe", label: "coriandre séchée" },
      { amount: 1, unit: "c. à soupe", label: "pâte de piment" },
      { amount: 2, unit: "c. à soupe", label: "sauce soja" },
      { amount: 2, unit: "c. à soupe", label: "vinaigre de riz ou assaisonnement sushi" },
      { amount: 1, label: "gousse d’ail hachée", kind: "whole" },
      { amount: 1, unit: "c. à soupe", label: "huile de sésame" },
      { amount: 1, unit: "c. à soupe", label: "jus de citron" },
      { label: "graines de sésame", kind: "fixed" },
    ],
    steps: [
      "Coupez le concombre en fines rondelles et émincez l’oignon rouge.",
      "Placez-les dans un saladier.",
      "Mélangez la coriandre, la pâte de piment, la sauce soja, le vinaigre de riz, l’ail, l’huile de sésame et le jus de citron.",
      "Versez la sauce dans le saladier, ajoutez les graines de sésame et mélangez bien.",
      "Laissez mariner 30 minutes au frais avant de servir.",
    ],
  },
  {
    slug: "tataki-saumon-pistache",
    title: "Tataki de saumon à la pistache",
    category: "entrées",
    portions: 2,
    prep: "15 min",
    rest: "Marinade : 12 h",
    illustration: "/illustrations/uniform/tataki-saumon-pistache.png",
    ingredients: [
      { amount: 2, label: "pavés de saumon", kind: "whole" },
      { amount: 30, label: "pistaches", kind: "whole" },
      { amount: 2, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 3, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 2, unit: "c. à soupe", label: "huile de sésame" },
      { amount: 0.5, label: "citron", kind: "fractional" },
      { label: "ail semoule", kind: "fixed" },
      { amount: 0.5, unit: "c. à soupe", label: "farine", kind: "fractional" },
    ],
    steps: [
      "Dans un plat creux, mélangez la sauce soja, le sirop d’agave, le jus du demi-citron, l’huile de sésame et l’ail semoule.",
      "Retirez la peau des pavés de saumon, déposez-les dans la marinade et laissez mariner le plus longtemps possible, idéalement 12 heures.",
      "Concassez finement les pistaches, jusqu’à obtenir une poudre grossière.",
      "Versez la marinade dans une petite casserole, ajoutez la farine et faites chauffer à feu doux jusqu’à obtenir une sauce onctueuse. Réservez.",
      "Roulez les pavés de saumon dans les pistaches sur toutes les faces, puis faites-les snacker à feu moyen 1 minute de chaque côté, soit environ 4 minutes au total.",
      "Coupez le saumon en tranches d’environ 1 cm, disposez-les dans les assiettes, versez un peu de sauce dessus et servez aussitôt.",
    ],
  },
  {
    slug: "salade-courgettes-feta-pignons",
    title: "Salade de courgettes marinées, feta & pignons",
    category: "entrées",
    portions: 2,
    prep: "15 min",
    rest: "Marinade : 2 h",
    illustration: "/illustrations/uniform/salade-courgettes-feta-pignons.png",
    ingredients: [
      { amount: 2, label: "courgettes", kind: "whole" },
      { amount: 4, unit: "c. à soupe", label: "huile d’olive" },
      { amount: 1, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 0.25, label: "citron jaune", kind: "fractional" },
      { amount: 0.25, unit: "c. à café", label: "ail en poudre", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "aneth séché" },
      { amount: 1, unit: "c. à soupe", label: "vinaigre balsamique" },
      { amount: 30, unit: "g", label: "feta" },
      { label: "sel et poivre", kind: "fixed" },
      { amount: 2, unit: "c. à soupe", label: "pignons de pin" },
    ],
    steps: [
      "Mélangez dans un bol l’huile d’olive, le sirop d’agave, le jus de citron, l’ail en poudre, l’aneth, le vinaigre balsamique, le sel et le poivre.",
      "Coupez les courgettes en fines lanières dans la longueur, puis faites-les griller à feu vif 2 à 3 minutes de chaque côté, jusqu’à ce qu’elles soient légèrement dorées mais encore fermes.",
      "Versez la marinade sur les courgettes encore chaudes. Mélangez bien, puis laissez mariner 2 heures au frais.",
      "Au moment de servir, ajoutez la feta émiettée et les pignons de pin torréfiés, puis mélangez délicatement.",
    ],
  },
  {
    slug: "salade-fattouche",
    title: "Salade fattouche",
    category: "entrées",
    portions: 2,
    prep: "20 min",
    cook: "10 min",
    illustration: "/illustrations/uniform/salade-fattouche.png",
    ingredients: [
      { label: "2 à 3 wraps", kind: "fixed" },
      { label: "quelques feuilles de salade iceberg", kind: "fixed" },
      { amount: 1, label: "tomate ou l’équivalent en tomates cerises", kind: "whole" },
      { amount: 0.5, label: "concombre", kind: "fractional" },
      { amount: 1, label: "avocat", kind: "whole", optional: true },
      { label: "cumin et paprika", kind: "fixed" },
      { label: "sel, poivre et huile d’olive", kind: "fixed" },
      { amount: 2, unit: "c. à soupe", label: "vinaigre de cidre" },
      { amount: 1, unit: "c. à soupe", label: "jus de citron" },
      { amount: 0.5, unit: "c. à café", label: "paprika", kind: "fractional" },
      { amount: 0.5, unit: "c. à café", label: "oignons séchés", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
    ],
    steps: [
      "Préchauffez le four à 220 °C.",
      "Coupez les wraps en rectangles et placez-les sur une plaque recouverte de papier cuisson.",
      "Ajoutez du cumin, du paprika, du sel, du poivre et de l’huile d’olive.",
      "Enfournez 10 minutes ou plus, jusqu’à ce que les bords soient bien croustillants. Laissez refroidir.",
      "Pendant ce temps, coupez finement la salade. Coupez les tomates et le concombre en petits cubes, puis l’avocat en cubes plus gros.",
      "Préparez la sauce en mélangeant tous les ingrédients.",
      "Mélangez tous les ingrédients, versez la sauce et dégustez rapidement pour que les morceaux de wraps restent croustillants.",
    ],
    note: "Vous pouvez saupoudrer de piment d’Espelette une fois la salade dressée.",
  },
  {
    slug: "salade-raviolis-pesto",
    title: "Salade de raviolis au pesto",
    category: "plats",
    portions: 2,
    prep: "20 min",
    cook: "20 min",
    illustration: "/illustrations/uniform/salade-raviolis-pesto.png",
    ingredients: [
      { amount: 250, unit: "g", label: "raviolis ricotta-épinard" },
      { amount: 20, label: "tomates cerises", kind: "whole" },
      { label: "huile d’olive, sel et poivre", kind: "fixed" },
      { label: "piment d’Espelette et herbes de Provence", kind: "fixed" },
      { amount: 4, unit: "poignées", label: "roquette" },
      { amount: 1, unit: "c. à soupe", label: "pignons de pin" },
      { amount: 1, label: "mozzarella di bufala", kind: "whole" },
      { amount: 2, unit: "c. à soupe", label: "pesto verde" },
      { amount: 1, unit: "c. à soupe", label: "huile d’olive extra vierge" },
      { amount: 3, unit: "c. à soupe", label: "vinaigre de cidre" },
      { amount: 1, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 1, unit: "c. à soupe", label: "vinaigre balsamique" },
      { amount: 1, unit: "c. à café", label: "herbes de Provence" },
      { amount: 0.25, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { amount: 1, unit: "c. à café", label: "échalote séchée" },
    ],
    steps: [
      "Préchauffez le four à 200 °C. Coupez les tomates cerises en deux, assaisonnez-les avec du sel, du poivre, du piment d’Espelette, des herbes de Provence et un filet d’huile d’olive. Enfournez 20 minutes, puis laissez refroidir.",
      "Faites cuire les raviolis dans de l’eau salée, selon le temps indiqué sur la boîte.",
      "Égouttez les raviolis. Faites-les ensuite dorer quelques minutes dans une poêle avec un filet d’huile d’olive, sur les deux faces, puis laissez refroidir.",
      "Mélangez tous les ingrédients de la sauce, goûtez et ajustez l’assaisonnement si besoin.",
      "Torréfiez les pignons de pin 1 minute dans une poêle bien chaude sans matière grasse.",
      "Mélangez les raviolis, les tomates cerises rôties et la roquette. Ajoutez la mozzarella coupée en cubes, arrosez généreusement de sauce au pesto, puis parsemez de pignons torréfiés et d’un peu de piment d’Espelette.",
    ],
  },
  {
    slug: "salade-thai",
    title: "Salade thaï",
    category: "plats",
    portions: 2,
    prep: "25 min",
    cook: "10 min",
    illustration: "/illustrations/uniform/salade-thai.png",
    ingredients: [
      { amount: 0.5, label: "carotte (environ 200 g)", kind: "fractional" },
      { amount: 1, label: "avocat", kind: "whole" },
      { amount: 200, unit: "g", label: "chou rouge" },
      { label: "vermicelles de riz (environ 60 g par personne)", kind: "fixed" },
      { amount: 10, label: "cacahuètes", kind: "whole" },
      { amount: 1, unit: "c. à café", label: "menthe séchée", optional: true },
      { label: "oignons frits", kind: "fixed", optional: true },
      { amount: 4, label: "œufs", kind: "whole" },
      { amount: 4, unit: "c. à soupe", label: "sauce soja salée" },
      { amount: 4, unit: "c. à café", label: "beurre de cacahuète" },
      { amount: 4, unit: "c. à café", label: "huile de sésame" },
      { amount: 4, unit: "c. à soupe", label: "vinaigre de riz ou assaisonnement sushi" },
      { amount: 4, unit: "c. à soupe", label: "sirop d’agave" },
      { amount: 0.5, unit: "c. à café", label: "oignons séchés", kind: "fractional" },
      { amount: 0.25, unit: "c. à café", label: "ail séché", kind: "fractional" },
      { label: "gingembre séché et poivre", kind: "fixed" },
    ],
    steps: [
      "Faites cuire ou réhydratez les vermicelles selon les indications du paquet. Égouttez-les, passez-les sous l’eau froide puis séparez-les avec une fourchette.",
      "Émincez très finement le chou rouge.",
      "Épluchez puis râpez grossièrement la carotte.",
      "Retirez la peau de l’avocat puis coupez-le en cubes.",
      "Concassez grossièrement les cacahuètes.",
      "Faites cuire les œufs 6 minutes à partir de l’ébullition. Refroidissez-les dans l’eau froide puis écalez-les.",
      "Mélangez tous les ingrédients de la sauce. Goûtez et réassaisonnez si besoin.",
      "Répartissez les vermicelles et les légumes dans les assiettes. Versez la sauce, ajoutez les cacahuètes, la menthe et les oignons frits. Coupez les œufs en deux, déposez-les sur le dessus puis salez légèrement.",
    ],
  },
  {
    slug: "saumon-en-croute",
    title: "Saumon en croûte",
    category: "plats",
    portions: 2,
    prep: "10 min",
    cook: "10 à 12 min",
    illustration: "/illustrations/uniform/saumon-en-croute.png",
    ingredients: [
      { amount: 2, label: "pavés de saumon", kind: "whole" },
      { amount: 2, unit: "c. à soupe", label: "paprika fumé" },
      { amount: 1, label: "gousse d’ail", kind: "whole" },
      { amount: 0.25, unit: "c. à café", label: "ail en poudre", kind: "fractional" },
      { amount: 1, unit: "c. à soupe", label: "jus de citron" },
      { amount: 3, unit: "c. à soupe", label: "huile d’olive" },
      { label: "sel et poivre", kind: "fixed" },
      { amount: 3, unit: "c. à soupe", label: "parmesan râpé" },
      { amount: 2, unit: "c. à soupe", label: "chapelure panko" },
      { amount: 1, unit: "c. à café", label: "ciboulette séchée" },
    ],
    steps: [
      "Préchauffez le four à 210 °C en chaleur statique. Retirez la peau du saumon, puis déposez les pavés dans un plat allant au four.",
      "Dans un bol, mélangez l’ail haché ou l’ail en poudre, le paprika fumé, le jus de citron et l’huile d’olive.",
      "Badigeonnez les pavés de sauce. Salez, poivrez, puis ajoutez le parmesan râpé et la chapelure panko sur le dessus.",
      "Enfournez 10 à 12 minutes selon l’épaisseur des pavés. À la sortie du four, parsemez de ciboulette séchée avant de servir.",
    ],
  },
  {
    slug: "tarte-au-chocolat",
    title: "Tarte au chocolat",
    category: "desserts",
    portions: 8,
    prep: "30 min",
    cook: "45 à 50 min",
    rest: "Repos : 4 h au frais",
    illustration: "/illustrations/uniform/tarte-au-chocolat.png",
    ingredients: [
      { amount: 280, unit: "g", label: "farine" },
      { label: "pincées de sel", kind: "fixed" },
      { amount: 134, unit: "g", label: "beurre froid" },
      { amount: 54, unit: "g", label: "sucre" },
      { amount: 1, label: "œuf", kind: "whole" },
      { amount: 3, label: "œufs", kind: "whole" },
      { amount: 267, unit: "g", label: "chocolat noir" },
      { amount: 27, unit: "cl", label: "crème liquide entière" },
    ],
    steps: [
      "Mélangez la farine, le sel, le sucre et le beurre froid coupé en morceaux jusqu’à obtenir une pâte ayant l’aspect d’un crumble.",
      "Ajoutez l’œuf et malaxez jusqu’à obtenir une pâte uniforme qui ne colle pas aux doigts.",
      "Formez une boule de pâte et réservez-la au frais 30 minutes à 4 heures.",
      "Sortez la pâte, étalez-la sur environ 5 mm d’épaisseur, placez-la dans le moule, piquez le fond avec une fourchette et remettez au frais 30 minutes.",
      "Préchauffez le four à 180 °C.",
      "Enfournez le fond de tarte garni de légumes secs ou de riz pendant 25 à 30 minutes, selon l’épaisseur de la pâte. Laissez refroidir.",
      "Dans un saladier, versez la crème chaude sur le chocolat coupé en morceaux. Mélangez jusqu’à obtenir une ganache sans morceaux, puis laissez refroidir un peu. Ajoutez les œufs et mélangez.",
      "Préchauffez le four à 170 °C. Versez la ganache dans le fond de tarte et enfournez 20 minutes en éteignant le four.",
      "Sortez la tarte et placez-la au frais pendant au moins 4 heures.",
    ],
    note: "Sortez la tarte du frais 15 minutes avant de servir pour profiter de toute l’onctuosité de la ganache.",
  },
];

export const featuredRecipes = recipes.filter((recipe) =>
  ["pates-burrata-pistaches", "courgettes-marinees-citron-thym", "banana-bread-healthy"].includes(recipe.slug),
);

export function getRecipe(slug: string) {
  return recipes.find((recipe) => recipe.slug === slug);
}
